# Generated by Django 3.1.7 on 2021-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodetransaksi', models.CharField(max_length=255)),
                ('jenistransaksi', models.CharField(choices=[('Pemasukan', 'Pemasukan)'), ('Pengeluaran', 'Pengeluaran')], default=None, max_length=25)),
                ('nominal', models.IntegerField()),
                ('keterangan', models.CharField(max_length=255)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
    ]
