# Generated by Django 3.1.7 on 2021-03-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kas',
            name='jenistransaksi',
            field=models.CharField(choices=[('Infaq', 'Infaq'), ('Pengeluaran', 'Pengeluaran')], default=None, max_length=25),
        ),
    ]
