# Generated by Django 3.1.7 on 2021-03-27 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_auto_20210327_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='kas',
            name='tanggaltransaksi',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
