# Generated by Django 3.1.7 on 2021-03-22 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skorpelanggaran', models.IntegerField()),
                ('kehadiransiswa', models.IntegerField()),
                ('siswa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datakegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='KehadiranSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalkbm', models.DateTimeField(default=datetime.datetime(2021, 3, 22, 14, 57, 21, 707913))),
                ('status', models.CharField(blank=True, choices=[('Hadir', 'Hadir)'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alfa', 'Alfa')], default='Hadir', max_length=100, null=True)),
                ('catatan', models.CharField(max_length=255)),
                ('datasiswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datasiswa')),
            ],
        ),
    ]
