# Generated by Django 3.1.7 on 2021-03-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20210319_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skorpelanggaran', models.IntegerField()),
                ('kehadiransiswa', models.IntegerField()),
                ('siswa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datakegiatan')),
            ],
        ),
    ]
