# Generated by Django 3.1.7 on 2021-03-22 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiransiswa',
            name='tanggalkbm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
