# Generated by Django 3.1.7 on 2021-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0002_auto_20210322_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiransiswa',
            name='tanggalkbm',
            field=models.DateField(),
        ),
    ]
