# Generated by Django 3.1.7 on 2021-03-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('kesiswaan', '0003_auto_20210322_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiransiswa',
            name='datasiswa',
        ),
        migrations.AddField(
            model_name='kehadiransiswa',
            name='datasiswa',
            field=models.ManyToManyField(to='home.DataSiswa'),
        ),
    ]
