# Generated by Django 3.1.7 on 2021-03-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0004_auto_20210327_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresiswa',
            name='kehadiransiswa',
        ),
        migrations.RemoveField(
            model_name='scoresiswa',
            name='siswa_id',
        ),
        migrations.AddField(
            model_name='scoresiswa',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scoresiswa',
            name='nama',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoresiswa',
            name='nislokal',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoresiswa',
            name='tanggalpelanggaran',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
