# Generated by Django 3.1.7 on 2021-03-27 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0005_auto_20210327_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresiswa',
            name='tanggalpelanggaran',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
