# Generated by Django 3.1.7 on 2021-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_auto_20210323_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='nominaldenda',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='pinjam',
            name='statuspinjaman',
            field=models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Denda', 'Denda')], default='Dipinjam', max_length=255),
        ),
    ]
