# Generated by Django 3.1.7 on 2021-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_auto_20210327_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='nominaldenda',
            field=models.IntegerField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
