# Generated by Django 3.1.7 on 2021-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0006_auto_20210327_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='nominaldenda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
