# Generated by Django 3.0.8 on 2021-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswaTambahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahunmasuk', models.CharField(choices=[('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021')], max_length=25)),
                ('statussiswa', models.CharField(choices=[('Pendaftar', 'Pendaftar'), ('Pindahan', 'Pindahan'), ('Aktif', 'Aktif'), ('Keluar', 'Keluar'), ('Lulus', 'Lulus')], max_length=25)),
                ('nislokal', models.CharField(max_length=255)),
            ],
        ),
    ]
