# Generated by Django 3.0.8 on 2021-03-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_2220'),
        ('psb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siswa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DataSiswa')),
            ],
        ),
    ]
