# Generated by Django 3.0.8 on 2021-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_2220'),
        ('psb', '0003_homedatasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedatasiswa',
            name='psbmodel',
        ),
        migrations.AddField(
            model_name='homedatasiswa',
            name='psbmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DataSiswa'),
        ),
    ]
