# Generated by Django 3.0.8 on 2021-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMotivasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataOrtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokk', models.CharField(max_length=255)),
                ('kepalakeluarga', models.CharField(max_length=255)),
                ('ayah', models.CharField(max_length=255)),
                ('tanggallahirayah', models.DateField()),
                ('statusayah', models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100)),
                ('nikayah', models.CharField(max_length=255)),
                ('pendidikanayah', models.CharField(choices=[('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100)),
                ('pekerjaanayah', models.CharField(choices=[('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100)),
                ('ibu', models.CharField(max_length=255)),
                ('tanggallahiribu', models.DateField()),
                ('statusibu', models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100)),
                ('nikibu', models.CharField(max_length=255)),
                ('pendidikanibu', models.CharField(choices=[('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100)),
                ('pekerjaanibu', models.CharField(choices=[('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100)),
                ('wali', models.CharField(max_length=255)),
                ('tanggallahirwali', models.DateField()),
                ('statuswali', models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100)),
                ('nikwali', models.CharField(max_length=255)),
                ('pendidikanwali', models.CharField(choices=[('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100)),
                ('pekerjaanwali', models.CharField(choices=[('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100)),
                ('penghasilan', models.CharField(choices=[('Kurang Dari Rp 500.000,-', 'Kurang Dari Rp 500.000,-'), ('Rp 500.000 - 1.000.000', 'Rp 500.000 - 1.000.000'), ('Rp 1.000.000 - 2.000.000', 'Rp 1.000.000 - 2.000.000'), ('Rp 2.000.000 - 3.000.000', 'Rp 2.000.000 - 3.000.000'), ('Rp 3.000.000 - 5.000.000', 'Rp 3.000.000 - 5.000.000'), ('Lebih Dari Rp 5.000.000', 'Lebih Dari Rp 5.000.000')], default=None, max_length=100)),
                ('kks', models.CharField(max_length=255)),
                ('pkh', models.CharField(max_length=255)),
                ('kip', models.CharField(max_length=255)),
                ('alamatortuwali', models.CharField(max_length=255)),
                ('sktm', models.CharField(choices=[('Ya', 'Ya (Harap Lampirkan SKTM kepada pihak Madrasah)'), ('Tidak', 'Tidak')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataSekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenislembaga', models.CharField(choices=[('SMP', 'SMP'), ('MTs', 'MTs'), ('Paket C', 'Paket C'), ('Lainnya', 'Lainnya')], default=None, max_length=25)),
                ('statuslemaga', models.CharField(choices=[('Negeri', 'Negeri'), ('Swasta', 'Swasta')], default=None, max_length=25)),
                ('npsn', models.CharField(max_length=255)),
                ('noijazah', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nisn', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=255)),
                ('tempatlahir', models.CharField(max_length=255)),
                ('tanggallahir', models.DateField()),
                ('jeniskelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default=None, max_length=25)),
                ('hobi', models.CharField(choices=[('Olahraga', 'Olahraga'), ('Kesenian', 'Kesenian'), ('Membaca', 'Membaca'), ('Menulis', 'Menulis'), ('Jalan-Jalan', 'Jalan-Jalan'), ('Lainnya', 'Lainnya')], default=None, max_length=25)),
                ('citacita', models.CharField(choices=[('PNS', 'PNS'), ('TNI/Porli', 'TNI/Porli'), ('Guru/Dosen', 'Guru/Dosen'), ('Dokter', 'Dokter'), ('Politikus', 'Politikus'), ('Wiraswasta', 'Wiraswasta'), ('Seniman/Artis', 'Seniman/Artis'), ('Ilmuan', 'Ilmuan'), ('Agamawan', 'Agamawan'), ('Lainnya', 'Lainnya')], default=None, max_length=25)),
                ('anakke', models.IntegerField()),
                ('jumlahsaudara', models.IntegerField()),
                ('sekolahasal', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataTinggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenistempattinggal', models.CharField(choices=[('Tinggal Dengan Orang Tua/Wali', 'Tinggal Dengan Orang Tua/Wali'), ('Ikut Saudara/Kerabat', 'Ikut Saudara/Kerabat'), ('Asrama Madrasah', 'Asrama Madrasah'), ('Kontrak/Kost', 'Kontrak/Kost'), ('Asrama Pesantren', 'Asrama Pesantren'), ('Panti Asuhan', 'Panti Asuhan'), ('Rumah Singgah', 'Rumah Singgah'), ('Lainnya', 'Lainnya')], default=None, max_length=100)),
                ('alamat', models.CharField(max_length=252)),
                ('provinsi', models.CharField(max_length=255)),
                ('kabupatenkota', models.CharField(max_length=255)),
                ('kecamatan', models.CharField(max_length=255)),
                ('desa', models.CharField(max_length=255)),
                ('kodepos', models.CharField(max_length=255)),
                ('jaraktinggal', models.CharField(choices=[('Kurang dari 5 KM', 'Kurang dari 5 KM'), ('Antara 5 - 10 KM', 'Antara 5 - 10 KM'), ('Antara 11 - 20 KM', 'Antara 11 - 20 KM'), ('Antara 21 - 30 KM', 'Antara 21 - 30 KM'), ('Lebih dari 30 KM', 'Lebih dari 30 KM')], default=None, max_length=100)),
                ('transportasi', models.CharField(choices=[('Jalan Kaki', 'Jalan Kaki'), ('Sepeda', 'Sepeda'), ('Sepeda Motor', 'Sepeda Motor'), ('Mobil Pribadi', 'Mobil Pribadi'), ('Antar Jemput Sekolah', 'Antar Jemput Sekolah'), ('Angkutan Umum', 'Angkutan Umum'), ('Perahu/Sampan', 'Perahu/Sampan'), ('Lainnya', 'Lainnya')], default=None, max_length=100)),
            ],
        ),
    ]
