# Generated by Django 3.0.8 on 2021-03-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nisn', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=255)),
                ('tempatlahir', models.CharField(max_length=255)),
                ('tanggallahir', models.DateField()),
                ('jeniskelamin', models.CharField(choices=[('1', 'Laki-Laki'), ('2', 'Perempuan')], default=None, max_length=1)),
                ('hobi', models.CharField(choices=[('1', 'Olahraga'), ('2', 'Kesenian'), ('3', 'Membaca'), ('4', 'Menulis'), ('5', 'Jalan-Jalan'), ('6', 'Lainnya')], default=None, max_length=1)),
                ('citacita', models.CharField(choices=[('1', 'PNS'), ('2', 'TNI/Porli'), ('3', 'Guru/Dosen'), ('4', 'Dokter'), ('5', 'Politikus'), ('6', 'Wiraswasta'), ('7', 'Seniman/Artis'), ('8', 'Ilmuan'), ('9', 'Agamawan'), ('10', 'Lainnya')], default=None, max_length=2)),
                ('anakke', models.IntegerField()),
                ('jumlahsaudara', models.IntegerField()),
                ('sekolahasal', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
