# Generated by Django 3.0.8 on 2021-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivasi', models.CharField(max_length=255)),
                ('statussiswa', models.CharField(choices=[('Pendaftar', 'Pendaftar'), ('Tidak Diterima', 'Tidak Diterima'), ('Pindahan', 'Pindahan'), ('Aktif', 'Aktif'), ('Keluar', 'Keluar'), ('Lulus', 'Lulus')], default='Pendaftar', max_length=100)),
                ('tahunmasuk', models.CharField(blank=True, max_length=25)),
                ('nislokal', models.CharField(blank=True, max_length=255)),
                ('kelas', models.CharField(blank=True, choices=[(' ', ' '), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=' ', max_length=100)),
                ('jurusan', models.CharField(blank=True, choices=[(' ', ' '), ('IIS', 'IIS'), ('IIK', 'IIK'), ('MIA', 'MIA')], default=' ', max_length=100, null=True)),
                ('poinpelanggaran', models.IntegerField(default=0, null=True)),
                ('pinjamanbuku', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataMotivasi',
        ),
    ]
