# Generated by Django 3.0.8 on 2021-03-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasiswa',
            name='anakke',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='citacita',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='hobi',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='jumlahsaudara',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='sekolahasal',
        ),
    ]
