# Generated by Django 3.0.8 on 2021-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataortu',
            name='tanggallahirwali',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datatinggal',
            name='alamat',
            field=models.CharField(max_length=255),
        ),
    ]
