# Generated by Django 3.1.7 on 2021-03-19 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210317_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='kegiatan',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='home.datakegiatan'),
            preserve_default=False,
        ),
    ]
