# Generated by Django 3.0.8 on 2021-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210305_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataortu',
            name='pekerjaanayah',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='pekerjaanibu',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='pekerjaanwali',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/Polisi', 'TNI/Polisi'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Wiraswasta/Wirausaha', 'Wiraswasta/Wirausaha'), ('Pengacara/Hakim/Jaksa/Notaris', 'Pengacara/Hakim/Jaksa/Notaris'), ('Seniman/Artis', 'Seniman/Artis'), ('Dokter/Perawat', 'Dokter/Perawat'), ('Pilot / Pramugara/i', 'Pilot / Pramugara/i'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh (Tani/Pabrik/Bangunan)', 'Buruh (Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('Lainnya', 'Lainnya')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='pendidikanayah',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='pendidikanibu',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='pendidikanwali',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('MI / SD / Sederajat', 'MI / SD / Sederajat'), ('MTs / SMP', 'MTs / SMP'), ('SMK / SMA / MA', 'SMK / SMA / MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4 / S1', 'D4 / S1'), ('S2', 'S2'), ('S3', 'S3')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='statusayah',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='statusibu',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataortu',
            name='statuswali',
            field=models.CharField(choices=[('', 'Silahkan Pilih'), ('Masih Hidup', 'Masih Hidup'), ('Sudah Meninggal', 'Sudah Meninggal'), ('Tidak Diketahui', 'Tidak Diketahui')], default=None, max_length=100),
        ),
    ]
