# Generated by Django 3.1.7 on 2021-03-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_datasiswa_kegiatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasiswa',
            name='kegiatan',
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='kegiatan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datakegiatan'),
        ),
    ]
